version: '3'
services:
  qabattle:
    image: qapropeller/qa-battle:latest
    network_mode: bridge
    container_name: qabattle
    ports:
      - 8080:8080

  selenoid-cm:
    image: aerokube/cm:latest-release
    container_name: cm
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config:/root/.aerokube/selenoid"
    environment:
      OVERRIDE_HOME: "$PWD/config/"
    command: ["selenoid", "configure", "--tmpfs", "128", "--browsers", "chrome", "--last-versions", "1"]

  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    container_name: selenoid
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/config:/etc/selenoid/"
      - "$PWD/opt:/opt/selenoid/video"
      - "$PWD/opt:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR="$PWD/opt"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
    links:
      - qabattle
