name: Autotests on Selenoid

on:
  push:
    branches-ignore:
      - '!master' # Push events to branches matching allure-report
    #paths-ignore:
    #- 'docs/**'

jobs:
  autotests:
    name: Run autotests on selenoid
    runs-on: ubuntu-latest
    #services:
    #  qa:
    #    image: qapropeller/qa-battle:latest
    #    ports:
    #      - 8081:8080
    steps:
      - name: Start web app
        run: docker run -d -p 8081:8080 --name qa qapropeller/qa-battle:latest

      - run: |
          export MY_CONTAINER_ID=$(docker ps --filter name=my_container --format {{.ID}})
          export LOCAL_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${MY_CONTAINER_ID})
          echo LOCAL_IP=${LOCAL_IP}

      - name: Start selenoid
        #uses: Xotabu4/selenoid-github-action@v1
        run: curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start

      - name: Curl
        run: curl http://localhost:8081/
        continue-on-error: true

      - name: Curl
        run: curl http://${LOCAL_IP}:8081/
        continue-on-error: true

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: mvn dependency:go-offline compile compiler:testCompile

      - name: Run Test
        if: always()
        run: mvn test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Keep Allure history
        run: cp -r $(pwd)/gh-pages/history/. $(pwd)/target/allure-results/history
        continue-on-error: true

      - name: Generate Allure report
        if: always()
        run: mvn allure:report
        continue-on-error: true

      #- uses: actions/upload-artifact@master
      #  with:
      #    name: allure-report
      #    path: target/site/allure-maven-plugin

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/site/allure-maven-plugin