name: Autotests on Selenoid

on:
  push:
    branches-ignore:
      - '!master' # Push events to branches matching allure-report
    #paths-ignore:
    #- 'docs/**'

jobs:
  autotests:
    name: Run autotests on selenoid
    runs-on: ubuntu-latest
    services:
      qabattle:
        image: qapropeller/qa-battle:latest
        ports:
          - 8080:8080
        options: --name qabattle
    env:
      network_1: ${{ job.services.network }}
      network_2: ${{ job.container.network }}
    steps:
      #- name: Start web app
      #  run: docker run -d -p 8081:8080 --name qa qapropeller/qa-battle:latest

      - name: Network
        run: echo $network_1 $network_2

      - name: Start selenoid
        #uses: Xotabu4/selenoid-github-action@v1
        run: curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --args "-container-network $network_1"

      - name: Curl
        run: curl http://localhost:8080/
        continue-on-error: true

      #- run: echo ${LOCAL_IP}
      #  continue-on-error: true

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: mvn dependency:go-offline compile compiler:testCompile

      - name: Run Test
        if: always()
        run: mvn test -Dbase.url=http://localhost:8080
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Keep Allure history
        run: cp -r $(pwd)/gh-pages/history/. $(pwd)/target/allure-results/history
        continue-on-error: true

      - name: Generate Allure report
        if: always()
        run: mvn allure:report
        continue-on-error: true

      #- uses: actions/upload-artifact@master
      #  with:
      #    name: allure-report
      #    path: target/site/allure-maven-plugin

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/site/allure-maven-plugin