name: Docker compose

on:
  push:
    branches-ignore:
      - '!master' # Push events to branches matching allure-report
    #paths-ignore:
    #- 'docs/**'

jobs:
  compose:
    name: Docker compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker compose
        run: docker-compose up -d

      - name: Curl webaapp
        run: curl http://localhost:8080/
        continue-on-error: true

      - name: Curl selenoid
        run: http://127.0.0.1:4444/status
        continue-on-error: true

      - name: Check containers
        if: always()
        continue-on-error: true
        run: |
          docker logs qabattle
          docker logs selenoid